services:
  client:
    name: client
    source:
      root: .
    build:
      builder: NIXPACKS
      buildCommand: npm install && npm run build:client
    deploy:
      static: true
      directory: apps/client/dist
      spa: true
    env:
      VITE_API_URL: ${API_URL}
      VITE_AUTH_APP_URL: ${CLIENT_URL}
      VITE_ADMIN_APP_URL: ${ADMIN_URL}

  admin:
    name: admin
    source:
      root: .
    build:
      builder: NIXPACKS
      buildCommand: npm install && npm run build:admin
    deploy:
      static: true
      directory: apps/admin/dist
      spa: true
    env:
      VITE_API_URL: ${API_URL}
      VITE_AUTH_APP_URL: ${CLIENT_URL}
      VITE_ADMIN_APP_URL: ${ADMIN_URL}

  api-server:
    name: api-server
    source:
      root: .
    build:
      builder: NIXPACKS
      buildCommand: npm install && npm run build:server
    deploy:
      startCommand: npm run start:server
      healthcheckPath: /api/health
    env:
      PORT: 5000
      NODE_ENV: production
